spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: zjoj-backend-user-service
          uri: lb://zjoj-backend-user-service
          predicates:
            - Path=/api/user/**
        - id: zjoj-backend-question-service
          uri: lb://zjoj-backend-question-service
          predicates:
            - Path=/api/question/**
        - id: zjoj-backend-judge-service
          uri: lb://zjoj-backend-judge-service
          predicates:
            - Path=/api/judge/**
  application:
    name: zjoj-backend-gateway
  main:
    web-application-type: reactive
server:
  port: 8101
knife4j:
  gateway:
    # 1.open gateway aggregation component
    enabled: true
    # 2. mode: discovery, don't need to manually
    strategy: discover
    discover:
      # ③ start discovery
      enabled: true
      # ④ swagger2
      version: swagger2
